### ISSUE TITLE
error compile

### ISSUE THREAD

**Issue by goga1902** [fuxey/Linux-System-Monitoring-Library#12]
` #include <filesystem>
          ^~~~~~~~~~~~
compilation terminated.
CMakeFiles/linuxmonitoring.dir/build.make:131: recipe for target 'CMakeFiles/linuxmonitoring.dir/linux_process_load.cpp.o' failed
make[3]: *** [CMakeFiles/linuxmonitoring.dir/linux_process_load.cpp.o] Error 1
CMakeFiles/Makefile2:82: recipe for target 'CMakeFiles/linuxmonitoring.dir/all' failed
make[2]: *** [CMakeFiles/linuxmonitoring.dir/all] Error 2
CMakeFiles/Makefile2:89: recipe for target 'CMakeFiles/linuxmonitoring.dir/rule' failed
make[1]: *** [CMakeFiles/linuxmonitoring.dir/rule] Error 2
Makefile:124: recipe for target 'linuxmonitoring' failed
make: *** [linuxmonitoring] Error 2
`
Hi. Please tell me what is wrong with the compilation?
Checked the cmake versions, everything matches what you have in this repository.
Error in Ubuntu operating system 18.04.5.
Thanks in advance!

**Comment by fuxey** [comment]
Hello @goga1902, 

thanks for reporting the issue! 
which compiler version do you use? 
the #include <filesystem> is a "newer" feature of the stl and at least on my compiler it is working 
See https://stackoverflow.com/questions/48312460/c17-filesystem-is-not-a-namespace-name 
maybe you have to update your compiler or you habe to use ```#include <experimental/filesystem>``` instead of ``` #include <filesystem>```


This is my compiler version: 
```
g++ --version
g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
